#!/bin/bash

# DOODAH - Web dashboard Control File
# STATE: Pre-Alpha

VERSION="1.0.1"
SERVICE=/etc/systemd/system/doodah.service

## AVAILABLE COMMAND LINE TOOLS
# doodah disable
# doodah enable
# doodah restart
# doodah start
# doodah status
# doodah stop
# doodah --help
# doodah help

check_service_exists () {
    if [ ! -f "$SERVICE" ]; then
        echo [unit] > $SERVICE
        echo Description=Web dashboard >> $SERVICE
        echo After=multi-user.target >> $SERVICE

        echo [Service] >> $SERVICE
        echo Type=simple >> $SERVICE
        echo ExecStart=/usr/bin/doodah.py >> $SERVICE
        echo Restart=on-abort >> $SERVICE
        echo StandardOutput=syslog >> $SERVICE
        echo StandardError=syslog >> $SERVICE
        echo SyslogIdentifier=Doodah >> $SERVICE
        echo >> $SERVICE
        echo [Install] >> $SERVICE
        echo WantedBy=multi-user.target >> $SERVICE
    fi
}

case $1 in
    "disable" )
    echo "# DISABLE"
    check_service_exists
    systemctl disable $SERVICE
    ;;
    "enable" )
    echo "# ENABLE"
    check_service_exists
    systemctl enable $SERVICE
    ;;
    "restart" )
    echo "# RESTART"
    check_service_exists
    systemctl restart $SERVICE
    ;;
    "start")
    echo "# START"
    check_service_exists
    systemctl start $SERVICE
    ;;
    "status")
    echo "# STATUS"
    check_service_exists
    systemctl status $SERVICE
    ;;
    "stop")
    echo "# STOP"
    check_service_exists
    systemctl stop $SERVICE
    ;;
    "help"|"--help")
    echo "# HELP"
    ;;
    "version"|"--version")
    echo "VERSION: $VERSION"
    ;;
    *)
    doodah.py
    ;;
esac

